default:
  postgres:
    driver: 'PostgreSQL'
    host: '172.16.33.76'
    uid: 'stat'
    pwd: 'stat'  
    port: 5432
    database: 'stat'

  clickhouse:
    host: '172.16.33.74'
    port: 8123
    user: 'default'
    password: ''  
    table: 'states'

  initial_values:
    begin_time_range: "2017-09-12"
    end_time_range: "2017-09-18"

cti:
  postgres:
    driver: 'PostgreSQL'
    host: '172.16.33.76'
    uid: 'stat'
    pwd: 'stat'  
    port: 5432
    database: 'stat'

  clickhouse:
    host: '172.16.33.74'
    port: 8123
    user: 'default'
    password: ''  
    table: 'view_states_tg1h'

  initial_values:
    begin_time_range: "2017-09-12"
    end_time_range: "2017-09-18"

media-tel:
  postgres:
    driver: 'PostgreSQL'
    host: '10.0.0.177'
    uid: 'puser'
    pwd: 'puser'  
    port: 5432
    database: 'channel_list'

  clickhouse:
    host: '10.0.0.234'
    port: 8123
    user: 'default'
    password: ''  
    table: 'view_simstates'

  initial_values:
    begin_time_range: "2017-03-01"
    end_time_range: "2017-03-02"


